/**
 * Spreadsheet access, schema creation, and legacy-data migration.
 * Stage 7 avoids repeated full-sheet migrations and caches sheet handles per execution.
 */

var __spreadsheetCache_ = null;
var __sheetCache_ = {};
var __sheetSchemaReady_ = {};

function getSpreadsheet_() {
  if (__spreadsheetCache_) return __spreadsheetCache_;
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  if (!ss) throw new Error('This script must be bound to a Google Spreadsheet.');
  __spreadsheetCache_ = ss;
  return ss;
}

function cachedSheet_(ss, name) {
  if (__sheetCache_[name]) return __sheetCache_[name];
  var sheet = ss.getSheetByName(name);
  if (sheet) __sheetCache_[name] = sheet;
  return sheet;
}

function rememberSheet_(name, sheet) {
  if (sheet) __sheetCache_[name] = sheet;
  return sheet;
}

function ensureUsersSheet_(ss) {
  ss = ss || getSpreadsheet_();
  var sheet = cachedSheet_(ss, USERS_SHEET);
  if (!sheet) sheet = rememberSheet_(USERS_SHEET, ss.insertSheet(USERS_SHEET));
  if (!__sheetSchemaReady_[USERS_SHEET]) {
    if (sheet.getLastRow() === 0) sheet.getRange(1, 1, 1, USER_HEADERS.length).setValues([USER_HEADERS]);
    __sheetSchemaReady_[USERS_SHEET] = true;
  }
  return sheet;
}

function dataMigrationProperties_() {
  try {
    return PropertiesService.getDocumentProperties();
  } catch (err) {
    return PropertiesService.getScriptProperties();
  }
}

function ensureRecordIdsMigratedOnce_(sheet) {
  var props = dataMigrationProperties_();
  var current = props.getProperty(DATA_MIGRATION_PROPERTY);
  if (current === DATA_MIGRATION_VERSION) return false;
  migrateRecordIds_(sheet);
  props.setProperty(DATA_MIGRATION_PROPERTY, DATA_MIGRATION_VERSION);
  return true;
}

function ensureDataSheet_(ss) {
  ss = ss || getSpreadsheet_();
  var sheet = cachedSheet_(ss, DATA_SHEET);

  if (!sheet) {
    var sheets = ss.getSheets();
    var fallback = null;

    // Prefer the legacy data sheet by recognizing its headers instead of relying on tab order.
    for (var i = 0; i < sheets.length; i++) {
      var n = sheets[i].getName();
      if (n === USERS_SHEET || n === SETTINGS_SHEET || n === SESSIONS_SHEET || n === IDEMPOTENCY_SHEET || n === AUDIT_SHEET) continue;
      if (!fallback) fallback = sheets[i];

      if (sheets[i].getLastRow() > 0 && sheets[i].getLastColumn() >= 5) {
        var headers = sheets[i].getRange(1, 1, 1, Math.min(sheets[i].getLastColumn(), 12)).getValues()[0].map(clean_);
        if (headers.indexOf('تاريخ البلاغ') !== -1 && headers.indexOf('وحدة المعالجة') !== -1) {
          sheet = sheets[i];
          break;
        }
      }
    }

    if (!sheet) sheet = fallback;
    if (sheet) sheet.setName(DATA_SHEET);
    else sheet = ss.insertSheet(DATA_SHEET);
    rememberSheet_(DATA_SHEET, sheet);
  }

  if (!__sheetSchemaReady_[DATA_SHEET]) {
    if (sheet.getLastRow() === 0) {
      sheet.getRange(1, 1, 1, DATA_HEADERS.length).setValues([DATA_HEADERS]);
      try { dataMigrationProperties_().setProperty(DATA_MIGRATION_PROPERTY, DATA_MIGRATION_VERSION); } catch (err) {}
      __sheetSchemaReady_[DATA_SHEET] = true;
      return sheet;
    }

    // Preserve the original 12 columns and append identifiers in M/N.
    var currentHeaders = sheet.getRange(1, 1, 1, Math.max(sheet.getLastColumn(), DATA_HEADERS.length)).getValues()[0];
    for (var h = 0; h < 12; h++) {
      if (!currentHeaders[h]) sheet.getRange(1, h + 1).setValue(DATA_HEADERS[h]);
    }
    if (clean_(currentHeaders[12]) !== DATA_HEADERS[12]) sheet.getRange(1, 13).setValue(DATA_HEADERS[12]);
    if (clean_(currentHeaders[13]) !== DATA_HEADERS[13]) sheet.getRange(1, 14).setValue(DATA_HEADERS[13]);

    ensureRecordIdsMigratedOnce_(sheet);
    __sheetSchemaReady_[DATA_SHEET] = true;
  }

  return sheet;
}

function migrateRecordIds_(sheet) {
  var lastRow = sheet.getLastRow();
  if (lastRow <= 1) return;

  var baseData = sheet.getRange(2, 1, lastRow - 1, DATA_HEADERS.length).getValues();
  var recordIds = [];
  var tripIds = [];
  var tripMap = {};
  var changed = false;

  // First preserve any IDs already generated by a previous/partial migration.
  for (var i = 0; i < baseData.length; i++) {
    var existingTripId = clean_(baseData[i][13]);
    var key = [normalizeDate_(baseData[i][1]), clean_(baseData[i][2]), clean_(baseData[i][3]), clean_(baseData[i][4])].join('|');
    if (existingTripId && key) tripMap[key] = existingTripId;
  }

  for (var r = 0; r < baseData.length; r++) {
    var row = baseData[r];
    if (!row[1] && !row[7] && !row[12] && !row[13]) {
      recordIds.push([row[12] || '']);
      tripIds.push([row[13] || '']);
      continue;
    }

    var recordId = clean_(row[12]);
    if (!recordId) {
      recordId = Utilities.getUuid();
      changed = true;
    }

    var tripId = clean_(row[13]);
    if (!tripId) {
      var tripKey = [normalizeDate_(row[1]), clean_(row[2]), clean_(row[3]), clean_(row[4])].join('|');
      if (!tripMap[tripKey]) tripMap[tripKey] = Utilities.getUuid();
      tripId = tripMap[tripKey];
      changed = true;
    }

    recordIds.push([recordId]);
    tripIds.push([tripId]);
  }

  if (changed) {
    sheet.getRange(2, 13, recordIds.length, 1).setValues(recordIds);
    sheet.getRange(2, 14, tripIds.length, 1).setValues(tripIds);
  }
}

function ensureSettingsSheet_(ss) {
  ss = ss || getSpreadsheet_();
  var sheet = cachedSheet_(ss, SETTINGS_SHEET);
  if (!sheet) {
    sheet = rememberSheet_(SETTINGS_SHEET, ss.insertSheet(SETTINGS_SHEET));
    sheet.getRange(1, 1, 1, SETTINGS_HEADERS.length).setValues([SETTINGS_HEADERS]);
    __sheetSchemaReady_[SETTINGS_SHEET] = true;
    return sheet;
  }

  if (__sheetSchemaReady_[SETTINGS_SHEET]) return sheet;

  if (sheet.getLastRow() === 0) {
    sheet.getRange(1, 1, 1, SETTINGS_HEADERS.length).setValues([SETTINGS_HEADERS]);
    __sheetSchemaReady_[SETTINGS_SHEET] = true;
    return sheet;
  }

  var a1 = sheet.getRange(1, 1).getValue();
  if (clean_(a1) !== SETTINGS_HEADERS[0]) {
    var legacy = null;
    try { legacy = JSON.parse(String(a1 || '')); } catch (err) { legacy = null; }
    var rows = [SETTINGS_HEADERS];
    for (var i = 0; i < SETTINGS_KEYS.length; i++) {
      var key = SETTINGS_KEYS[i];
      rows.push([key, JSON.stringify(legacy && legacy[key] != null ? legacy[key] : defaultSettingValue_(key)), new Date()]);
    }
    // Replace the legacy JSON cell only after the normalized table is ready.
    sheet.getRange(1, 1, rows.length, 3).setValues(rows);
    var legacyLastRow = sheet.getLastRow();
    if (legacyLastRow > rows.length) {
      sheet.getRange(rows.length + 1, 1, legacyLastRow - rows.length, Math.max(3, sheet.getLastColumn())).clearContent();
    }
  }

  __sheetSchemaReady_[SETTINGS_SHEET] = true;
  return sheet;
}

function readSettingsObject_(sheet) {
  var data = sheet.getDataRange().getValues();
  var obj = {};
  for (var i = 1; i < data.length; i++) {
    var key = clean_(data[i][0]);
    if (!key) continue;
    try { obj[key] = JSON.parse(String(data[i][1] || 'null')); }
    catch (err) { obj[key] = defaultSettingValue_(key); }
  }
  for (var k = 0; k < SETTINGS_KEYS.length; k++) {
    var wanted = SETTINGS_KEYS[k];
    if (obj[wanted] == null) obj[wanted] = defaultSettingValue_(wanted);
  }
  return obj;
}

function defaultSettingValue_(key) {
  return key === 'healthAdmins' ? {} : [];
}

function ensureSessionsSheet_(ss) {
  ss = ss || getSpreadsheet_();
  var sheet = cachedSheet_(ss, SESSIONS_SHEET);
  if (!sheet) {
    sheet = rememberSheet_(SESSIONS_SHEET, ss.insertSheet(SESSIONS_SHEET));
    sheet.getRange(1, 1, 1, SESSION_HEADERS.length).setValues([SESSION_HEADERS]);
    try { sheet.hideSheet(); } catch (err) {}
    __sheetSchemaReady_[SESSIONS_SHEET] = true;
  } else if (!__sheetSchemaReady_[SESSIONS_SHEET]) {
    if (sheet.getLastRow() === 0) sheet.getRange(1, 1, 1, SESSION_HEADERS.length).setValues([SESSION_HEADERS]);
    __sheetSchemaReady_[SESSIONS_SHEET] = true;
  }
  return sheet;
}

function ensureIdempotencySheet_(ss) {
  ss = ss || getSpreadsheet_();
  var sheet = cachedSheet_(ss, IDEMPOTENCY_SHEET);
  if (!sheet) {
    sheet = rememberSheet_(IDEMPOTENCY_SHEET, ss.insertSheet(IDEMPOTENCY_SHEET));
    sheet.getRange(1, 1, 1, IDEMPOTENCY_HEADERS.length).setValues([IDEMPOTENCY_HEADERS]);
    try { sheet.hideSheet(); } catch (err) {}
    __sheetSchemaReady_[IDEMPOTENCY_SHEET] = true;
  } else if (!__sheetSchemaReady_[IDEMPOTENCY_SHEET]) {
    if (sheet.getLastRow() === 0) sheet.getRange(1, 1, 1, IDEMPOTENCY_HEADERS.length).setValues([IDEMPOTENCY_HEADERS]);
    __sheetSchemaReady_[IDEMPOTENCY_SHEET] = true;
  }
  return sheet;
}


function ensureAuditSheet_(ss) {
  ss = ss || getSpreadsheet_();
  var sheet = cachedSheet_(ss, AUDIT_SHEET);
  if (!sheet) {
    sheet = rememberSheet_(AUDIT_SHEET, ss.insertSheet(AUDIT_SHEET));
    sheet.getRange(1, 1, 1, AUDIT_HEADERS.length).setValues([AUDIT_HEADERS]);
    try { sheet.hideSheet(); } catch (err) {}
    __sheetSchemaReady_[AUDIT_SHEET] = true;
  } else if (!__sheetSchemaReady_[AUDIT_SHEET]) {
    if (sheet.getLastRow() === 0) {
      sheet.getRange(1, 1, 1, AUDIT_HEADERS.length).setValues([AUDIT_HEADERS]);
    } else {
      var current = sheet.getRange(1, 1, 1, Math.max(sheet.getLastColumn(), AUDIT_HEADERS.length)).getValues()[0];
      for (var i = 0; i < AUDIT_HEADERS.length; i++) {
        if (clean_(current[i]) !== AUDIT_HEADERS[i]) sheet.getRange(1, i + 1).setValue(AUDIT_HEADERS[i]);
      }
    }
    try { sheet.hideSheet(); } catch (err) {}
    __sheetSchemaReady_[AUDIT_SHEET] = true;
  }
  return sheet;
}
